---
name: Check Compatibility

on:
  pull_request_target

jobs:
  build:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run compatibility task
        run: ./gradlew checkCompatibility -i | tee $HOME/gradlew-check.out

      - name: Get results
        run: |
          echo '## Compatibility status:' > "${{ github.workspace }}/results.txt"
          echo "Checks if related components are compatible with change $(git rev-parse --short HEAD)" >> "${{ github.workspace }}/results.txt"
          echo "### Incompatible components" >> "${{ github.workspace }}/results.txt" && grep -e 'Incompatible component' $HOME/gradlew-check.out | sed -e 's/Incompatible component: \[\(.*\)\]/- \1/' >> "${{ github.workspace }}/results.txt"
          echo "### Skipped components"      >> "${{ github.workspace }}/results.txt" && grep -e 'Skipped component'      $HOME/gradlew-check.out | sed -e 's/Skipped component: \[\(.*\)\]/- \1/'      >> "${{ github.workspace }}/results.txt"
          echo "### Compatible components"   >> "${{ github.workspace }}/results.txt" && grep -e 'Compatible component'   $HOME/gradlew-check.out | sed -e 's/Compatible component: \[\(.*\)\]/- \1/'   >> "${{ github.workspace }}/results.txt"

      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 22958780

      - name: Add comment on the PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          issue-number: ${{ github.event.number }}
          body-path: "${{ github.workspace }}/results.txt"
